(ns digdir.config.api-keys
  (:require [clojure.string :as str]
            [digdir.config.structure :as structure]
            [clojure.tools.logging :as log]
            [datahike.api :as d]
            [digdir.data.db :as db]
            [digdir.config.db :as config-db]
            [digdir.config.audit :as audit]
            [nano-id.core :refer [nano-id]]
            [tick.core :as t]))

;; API Key Generation and Management
;;
;; This namespace provides functions for generating, storing, validating,
;; and revoking API keys used for authentication to the RAG API endpoint.
;;
;; Features:
;; - API keys are 32-byte random hex strings (256 bits of entropy)
;; - Only SHA-256 digests and non-secret display metadata are stored
;; - Legacy plaintext rows are upgraded after a successful authentication
;; - Keys can be revoked without deletion (maintains audit trail)
;; - Last-used timestamp is tracked for monitoring
;; - All operations are logged to the audit log

(defn generate-api-key
  "Generate a secure random API key (32-byte hex string).
  Format: 'rag_' prefix followed by 64 hex characters.
  Example: rag_a1b2c3d4e5f6...

  The 'rag_' prefix makes it easy to identify RAG API keys in logs/code."
  []
  (let [random-bytes (byte-array 32)]
    (doto (java.security.SecureRandom.)
      (.nextBytes random-bytes))
    (str "rag_" (apply str (map #(format "%02x" %) random-bytes)))))

(defn api-key-digest
  "Return the lowercase SHA-256 digest used to look up an API key.

  API keys contain 256 bits generated by SecureRandom, so an offline preimage
  attack remains infeasible without a server-side pepper. Using an unkeyed
  digest also avoids introducing a second bootstrap secret whose loss would
  invalidate every deployed key. The plaintext is never used as a database
  identity for newly-created or imported keys."
  [api-key]
  (when api-key
    (let [digest (.digest (java.security.MessageDigest/getInstance "SHA-256")
                          (.getBytes ^String api-key java.nio.charset.StandardCharsets/UTF_8))]
      (apply str (map #(format "%02x" (bit-and (int %) 0xff)) digest)))))

(defn api-key-display-metadata
  "Return non-secret fields suitable for key lists and audit displays."
  [api-key]
  (when api-key
    (let [length (count api-key)]
      {:api-key/prefix (subs api-key 0 (min 8 length))
       :api-key/last-four (subs api-key (max 0 (- length 4)))})))

(def valid-scopes
  "Set of valid API key scopes"
  #{:query :ingest :admin})

;; DERIVED, NOT DECLARED — see the note on `digdir.config.db/config-roots`.
;; These two sets were independent and identical by coincidence.
(def ^:private valid-config-roots structure/config-roots)

(defn- normalize-dataset-scope
  [dataset-scope]
  (let [tenant (or (:tenant dataset-scope) (get dataset-scope "tenant"))
        dataset-config-key (or (:dataset-config-key dataset-scope)
                               (get dataset-scope "dataset-config-key")
                               (get dataset-scope "dataset_config_key")
                               (:tenant-config-key dataset-scope)
                               (get dataset-scope "tenant-config-key")
                               (get dataset-scope "tenant_config_key")
                               (:config-key dataset-scope)
                               (get dataset-scope "config-key")
                               (get dataset-scope "config_key"))]
    (when (and (string? tenant)
               (string? dataset-config-key)
               (not (str/blank? tenant))
               (not (str/blank? dataset-config-key)))
      {:tenant tenant
       :dataset-config-key dataset-config-key})))

(defn- distinct-by*
  [f coll]
  (let [[_ result]
        (reduce (fn [[seen acc] item]
                  (let [k (f item)]
                    (if (contains? seen k)
                      [seen acc]
                      [(conj seen k) (conj acc item)])))
                [#{} []]
                coll)]
    result))

(defn- normalize-dataset-scopes
  [{:keys [dataset-scopes]}]
  (->> (map normalize-dataset-scope (or dataset-scopes []))
       (remove nil?)
       (distinct-by* (juxt :tenant :dataset-config-key))
       vec))

(defn- normalize-scope
  [scope]
  (cond
    (keyword? scope) scope
    (symbol? scope) (keyword (name scope))
    (string? scope) (let [s (str/trim scope)]
                      (when-not (str/blank? s)
                        (keyword (str/replace s #"^:+"
                                              ""))))
    :else nil))

(defn- normalize-scopes
  [scopes]
  (->> (or scopes [])
       (map normalize-scope)
       (filter valid-scopes)
       distinct
       vec))

(defn- normalize-agent-ref
  [agent-ref]
  (let [agent-id (cond
                   (string? agent-ref) agent-ref
                   (keyword? agent-ref) (name agent-ref)
                   (map? agent-ref) (or (:agent-id agent-ref)
                                        (:agent/id agent-ref)
                                        (get agent-ref "agent-id")
                                        (get agent-ref "agent/id"))
                   :else nil)]
    (when (and (string? agent-id) (not (str/blank? agent-id)))
      agent-id)))

(defn- normalize-agent-refs
  [agent-refs]
  (->> (or agent-refs [])
       (map normalize-agent-ref)
       (remove nil?)
       distinct
       vec))

(defn- normalize-config-key-string
  [v]
  (cond
    (nil? v) nil
    (string? v) (let [s (str/trim v)]
                  (when-not (str/blank? s)
                    s))
    (keyword? v) (let [s (name v)]
                   (when-not (str/blank? s)
                     s))
    (symbol? v) (let [s (str v)]
                  (when-not (str/blank? s)
                    s))
    :else (let [s (str v)]
            (when-not (str/blank? s)
              s))))

(defn- normalize-allowed-config-key
  [allowed-config-key]
  (let [root (some-> (or (:root allowed-config-key)
                         (:api-key.allowed-config-key/root allowed-config-key)
                         (get allowed-config-key "root")
                         (get allowed-config-key "api-key.allowed-config-key/root"))
                     keyword)
        tenant (or (:tenant allowed-config-key)
                   (:api-key.allowed-config-key/tenant allowed-config-key)
                   (get allowed-config-key "tenant")
                   (get allowed-config-key "api-key.allowed-config-key/tenant"))
        node-id (normalize-config-key-string
                 (or (:node-id allowed-config-key)
                     (:api-key.allowed-config-key/node-id allowed-config-key)
                     (get allowed-config-key "node-id")
                     (get allowed-config-key "api-key.allowed-config-key/node-id")))
        tenant-config-key (or (case root
                                :platform (or (:platform-config-key allowed-config-key)
                                              (get allowed-config-key "platform-config-key")
                                              (get allowed-config-key "platform_config_key"))
                                :runtime (or (:runtime-config-key allowed-config-key)
                                             (get allowed-config-key "runtime-config-key")
                                             (get allowed-config-key "runtime_config_key"))
                                :dataset (or (:dataset-config-key allowed-config-key)
                                             (get allowed-config-key "dataset-config-key")
                                             (get allowed-config-key "dataset_config_key"))
                                nil)
                              (:tenant-config-key allowed-config-key)
                              (:api-key.allowed-config-key/tenant-config-key allowed-config-key)
                              (get allowed-config-key "tenant-config-key")
                              (get allowed-config-key "tenant_config_key")
                              (:config-key allowed-config-key)
                              (get allowed-config-key "config-key")
                              (get allowed-config-key "config_key")
                              (get allowed-config-key "api-key.allowed-config-key/tenant-config-key"))]
    (when-not (contains? valid-config-roots root)
      (throw (ex-info "Invalid allowed config key root"
                      {:root root
                       :valid-roots (sort valid-config-roots)})))
    (when-not (and (string? (normalize-config-key-string tenant))
                   (not (str/blank? (normalize-config-key-string tenant))))
      (throw (ex-info "Allowed config key tenant is required"
                      {:tenant tenant})))
    (when-not (or (and node-id (not (str/blank? node-id)))
                  (and (normalize-config-key-string tenant-config-key)
                       (not (str/blank? (normalize-config-key-string tenant-config-key)))))
      (throw (ex-info "Allowed config key requires node-id or tenant-config-key"
                      {:root root
                       :tenant tenant})))
    {:root root
     :tenant (normalize-config-key-string tenant)
     :node-id node-id
     :tenant-config-key (normalize-config-key-string tenant-config-key)}))

(defn- normalize-allowed-config-keys
  [allowed-config-keys]
  (->> (or allowed-config-keys [])
       (map normalize-allowed-config-key)
       (distinct-by* (juxt :root :tenant :node-id :tenant-config-key))
       vec))

(defn- normalize-pulled-allowed-config-key
  [allowed-config-key]
  (let [{:keys [root tenant node-id tenant-config-key]}
        (normalize-allowed-config-key {:root (:api-key.allowed-config-key/root allowed-config-key)
                                       :tenant (:api-key.allowed-config-key/tenant allowed-config-key)
                                       :node-id (:api-key.allowed-config-key/node-id allowed-config-key)
                                       :tenant-config-key (:api-key.allowed-config-key/tenant-config-key allowed-config-key)})]
    (cond-> {:api-key.allowed-config-key/id (:api-key.allowed-config-key/id allowed-config-key)
             :api-key.allowed-config-key/root root
             :api-key.allowed-config-key/tenant tenant}
      node-id
      (assoc :api-key.allowed-config-key/node-id node-id)

      tenant-config-key
      (assoc :api-key.allowed-config-key/tenant-config-key tenant-config-key)

      (:api-key.allowed-config-key/created-at allowed-config-key)
      (assoc :api-key.allowed-config-key/created-at (:api-key.allowed-config-key/created-at allowed-config-key)))))

(defn- dataset-scopes->tenants
  [dataset-scopes]
  (->> dataset-scopes (map :tenant) distinct vec))

(defn- build-dataset-scope-tx-data
  [dataset-scopes]
  (mapv (fn [{:keys [tenant dataset-config-key]}]
          (let [ref-id (str "api-key-dataset-scope-" (nano-id))]
            {:api-key.dataset-scope/id ref-id
             :api-key.dataset-scope/tenant tenant
             :api-key.dataset-scope/dataset-config-key (or dataset-config-key "default")}))
        dataset-scopes))

(defn- build-agent-ref-tx-data
  [agent-refs]
  (mapv (fn [agent-id]
          (let [ref-id (str "api-key-agent-ref-" (nano-id))]
            {:api-key.agent-ref/id ref-id
             :api-key.agent-ref/agent-id agent-id}))
        agent-refs))

(defn- resolve-allowed-config-key-node!
  [conn {:keys [root tenant node-id tenant-config-key]}]
  (let [config-db-value (or (some-> (config-db/get-conn) deref)
                            @conn)
        node (cond
               node-id (config-db/get-config-node config-db-value node-id)
               tenant-config-key (config-db/get-config-node-by-tenant-config-key config-db-value tenant root tenant-config-key)
               :else nil)]
    (when-not node
      (throw (ex-info "Allowed config key references unknown config node"
                      {:root root
                       :tenant tenant
                       :node-id node-id
                       :tenant-config-key tenant-config-key})))
    (when-not (:config.node/enabled? node)
      (throw (ex-info "Allowed config key references disabled config node"
                      {:root root
                       :tenant tenant
                       :node-id (:config.node/id node)
                       :tenant-config-key (:config.node/tenant-config-key node)})))
    (when-not (= root (:config.node/root node))
      (throw (ex-info "Allowed config key root mismatch"
                      {:root root
                       :tenant tenant
                       :node-id (:config.node/id node)
                       :node-root (:config.node/root node)})))
    (when-not (= tenant (:config.node/tenant node))
      (throw (ex-info "Allowed config key tenant mismatch"
                      {:root root
                       :tenant tenant
                       :node-id (:config.node/id node)
                       :node-tenant (:config.node/tenant node)})))
    (when (str/blank? (:config.node/tenant-config-key node))
      (throw (ex-info "Allowed config key node must have a stable tenant-config-key"
                      {:root root
                       :tenant tenant
                       :node-id (:config.node/id node)})))
    node))

(defn- resolvable-main-db-config-node-ref
  [db node-id]
  (when-not (str/blank? node-id)
    (try
      (when (config-db/get-config-node db node-id)
        [:config.node/id node-id])
      (catch Exception _
        nil))))

(defn- build-allowed-config-key-tx-data
  [conn allowed-config-keys]
  (mapv (fn [{:keys [root tenant node-id tenant-config-key]}]
          (let [main-db @conn
                node (resolve-allowed-config-key-node! conn {:root root
                                                             :tenant tenant
                                                             :node-id node-id
                                                             :tenant-config-key tenant-config-key})
                allowed-config-key-id (str "api-key-allowed-config-key-" (nano-id))]
            (cond-> {:api-key.allowed-config-key/id allowed-config-key-id
                     :api-key.allowed-config-key/root root
                     :api-key.allowed-config-key/tenant tenant
                     :api-key.allowed-config-key/node-id (:config.node/id node)
                     :api-key.allowed-config-key/tenant-config-key (:config.node/tenant-config-key node)
                     :api-key.allowed-config-key/created-at (.getTime (t/inst (t/now)))}
              (resolvable-main-db-config-node-ref main-db (:config.node/id node))
              (assoc :api-key.allowed-config-key/node
                     (resolvable-main-db-config-node-ref main-db (:config.node/id node))))))
        allowed-config-keys))

(defn- resolve-eid-by-attr
  [db attr value]
  (d/q '[:find ?e .
         :in $ ?attr ?value
         :where [?e ?attr ?value]]
       db
       attr
       value))

(defn- resolve-eids-by-attr
  [db attr entities]
  (mapv (fn [entity]
          (let [value (get entity attr)
                eid (resolve-eid-by-attr db attr value)]
            (when-not eid
              (throw (ex-info "Failed to resolve API key child entity"
                              {:attr attr
                               :value value})))
            eid))
        entities))

(defn- build-parent-ref-assertions
  [api-key-eid attr ref-eids]
  (mapv (fn [ref-eid]
          [:db/add api-key-eid attr ref-eid])
        ref-eids))

(defn- transact-ref-assertions!
  [conn ref-assertions]
  (when (seq ref-assertions)
    (d/transact conn {:tx-data (vec ref-assertions)})))

(def ^:private api-key-base-pull-pattern
  '[:api-key/id
    :api-key/key-digest
    :api-key/prefix
    :api-key/last-four
    :api-key/name
    {:api-key/policy [:access-policy/id]}
    :api-key/tenants
    :api-key/clients
    :api-key/skill-graphs
    :api-key/scopes
    :api-key/created
    :api-key/created-by
    :api-key/revoked
    :api-key/last-used
    :api-key/usage-count
    :api-key/expires-at])

(def ^:private access-policy-base-pull-pattern
  '[:access-policy/id
    :access-policy/name
    :access-policy/tenants
    :access-policy/clients
    :access-policy/skill-graphs
    :access-policy/scopes
    :access-policy/created
    :access-policy/created-by])

(declare normalize-key-entity)
(declare normalize-access-policy-entity)

(defn- query-access-policy-dataset-scopes
  [db policy-id]
  (let [ref-eids (d/q '[:find [?ref ...]
                        :in $ ?policy-id
                        :where
                        [?p :access-policy/id ?policy-id]
                        [?p :access-policy/dataset-scopes ?ref]]
                      db policy-id)]
    (->> ref-eids
         (filter some?)
         (keep (fn [ref-eid]
                 (when (or (not (coll? ref-eid))
                           (and (vector? ref-eid) (= 2 (count ref-eid))))
                   (try
                     (d/pull db '[:api-key.dataset-scope/id
                                  :api-key.dataset-scope/tenant
                                  :api-key.dataset-scope/dataset-config-key]
                             ref-eid)
                     (catch Exception _
                       nil)))))
         (remove nil?)
         vec)))

(defn- query-access-policy-agent-refs
  [db policy-id]
  (let [rows (d/q '[:find ?ref-id ?agent-id
                    :in $ ?policy-id
                    :where
                    [?p :access-policy/id ?policy-id]
                    [?p :access-policy/agent-refs ?ref]
                    [?ref :api-key.agent-ref/id ?ref-id]
                    [?ref :api-key.agent-ref/agent-id ?agent-id]]
                  db policy-id)]
    (if (coll? rows)
      (mapv (fn [[ref-id agent-id]]
              {:api-key.agent-ref/id ref-id
               :api-key.agent-ref/agent-id agent-id})
            rows)
      [])))

(defn- query-access-policy-allowed-config-keys
  [db policy-id]
  (let [raw-refs (d/q '[:find [?ref ...]
                        :in $ ?policy-id
                        :where
                        [?p :access-policy/id ?policy-id]
                        [?p :access-policy/allowed-config-keys ?ref]]
                      db policy-id)]
    (->> raw-refs
         (filter some?)
         (keep (fn [ref]
                 (when (or (not (coll? ref))
                           (and (vector? ref) (= 2 (count ref))))
                   (try
                     (d/pull db '[:api-key.allowed-config-key/id
                                  :api-key.allowed-config-key/root
                                  :api-key.allowed-config-key/tenant
                                  :api-key.allowed-config-key/node-id
                                  :api-key.allowed-config-key/tenant-config-key
                                  :api-key.allowed-config-key/created-at]
                             ref)
                     (catch Exception _
                       nil)))))
         (remove nil?)
         vec)))

(defn- pull-access-policy-entity
  [db policy-id]
  (when-let [base-entity (d/pull db access-policy-base-pull-pattern [:access-policy/id policy-id])]
    (normalize-access-policy-entity
     (assoc base-entity
            :access-policy/dataset-scopes (query-access-policy-dataset-scopes db policy-id)
            :access-policy/agent-refs (query-access-policy-agent-refs db policy-id)
            :access-policy/allowed-config-keys (query-access-policy-allowed-config-keys db policy-id)))))

(defn- normalize-access-policy-entity
  [policy-entity]
  (let [dataset-scopes (mapv (fn [dataset-scope]
                               {:tenant (:api-key.dataset-scope/tenant dataset-scope)
                                :dataset-config-key (:api-key.dataset-scope/dataset-config-key dataset-scope)})
                             (:access-policy/dataset-scopes policy-entity))
        tenants (if (seq (:access-policy/tenants policy-entity))
                  (vec (:access-policy/tenants policy-entity))
                  (dataset-scopes->tenants dataset-scopes))
        agent-refs (->> (:access-policy/agent-refs policy-entity)
                        (mapv :api-key.agent-ref/agent-id))
        allowed-config-keys (->> (:access-policy/allowed-config-keys policy-entity)
                                 (mapv normalize-pulled-allowed-config-key)
                                 vec)]
    (-> policy-entity
        (assoc :access-policy/dataset-scopes dataset-scopes
               :access-policy/agent-refs agent-refs
               :access-policy/allowed-config-keys allowed-config-keys
               :access-policy/tenants tenants
               :access-policy/clients (vec (:access-policy/clients policy-entity))
               :access-policy/skill-graphs (vec (:access-policy/skill-graphs policy-entity))
               :access-policy/scopes (normalize-scopes (:access-policy/scopes policy-entity))))))

(defn- query-api-key-dataset-scopes
  [db api-key-id]
  (let [ref-eids (d/q '[:find [?ref ...]
                        :in $ ?api-key-id
                        :where
                        [?api-key :api-key/id ?api-key-id]
                        [?api-key :api-key/dataset-scopes ?ref]]
                      db api-key-id)]
    (->> ref-eids
         (filter some?)
         (keep (fn [ref-eid]
                 (when (or (not (coll? ref-eid))
                           (and (vector? ref-eid) (= 2 (count ref-eid))))
                   (try
                     (d/pull db '[:api-key.dataset-scope/id
                                  :api-key.dataset-scope/tenant
                                  :api-key.dataset-scope/dataset-config-key]
                             ref-eid)
                     (catch Exception _
                       nil)))))
         (remove nil?)
         vec)))

(defn- query-api-key-agent-refs
  [db api-key-id]
  (let [rows (d/q '[:find ?ref-id ?agent-id
                    :in $ ?api-key-id
                    :where
                    [?api-key :api-key/id ?api-key-id]
                    [?api-key :api-key/agent-refs ?ref]
                    [?ref :api-key.agent-ref/id ?ref-id]
                    [?ref :api-key.agent-ref/agent-id ?agent-id]]
                  db api-key-id)]
    (if (coll? rows)
      (mapv (fn [[ref-id agent-id]]
              {:api-key.agent-ref/id ref-id
               :api-key.agent-ref/agent-id agent-id})
            rows)
      [])))

(defn- query-api-key-allowed-config-keys
  [db api-key-id]
  (let [raw-refs (d/q '[:find [?ref ...]
                        :in $ ?api-key-id
                        :where
                        [?api-key :api-key/id ?api-key-id]
                        [?api-key :api-key/allowed-config-keys ?ref]]
                      db api-key-id)]
    (->> raw-refs
         (filter some?)
         (keep (fn [ref]
                 (when (or (not (coll? ref))
                           (and (vector? ref) (= 2 (count ref))))
                   (try
                     (d/pull db '[:api-key.allowed-config-key/id
                                  :api-key.allowed-config-key/root
                                  :api-key.allowed-config-key/tenant
                                  :api-key.allowed-config-key/node-id
                                  :api-key.allowed-config-key/tenant-config-key
                                  :api-key.allowed-config-key/created-at]
                             ref)
                     (catch Exception _
                       nil)))))
         (remove nil?)
         vec)))

(defn- api-key-id-by-digest
  [db digest]
  (d/q '[:find ?api-key-id .
         :in $ ?digest
         :where
         [?e :api-key/key-digest ?digest]
         [?e :api-key/id ?api-key-id]]
       db digest))

(defn- legacy-api-key-id-by-plaintext
  "Lookup retained solely for rows created before hashed storage shipped."
  [db api-key]
  (d/q '[:find ?api-key-id .
         :in $ ?api-key
         :where
         [?e :api-key/key ?api-key]
         [?e :api-key/id ?api-key-id]]
       db api-key))

(defn- api-key-ids-by-created-by
  [db user-id]
  (d/q '[:find [?api-key-id ...]
         :in $ ?user-id
         :where
         [?e :api-key/created-by ?user-id]
         [?e :api-key/id ?api-key-id]]
       db user-id))

(defn- pull-api-key-entity
  [db api-key-id]
  (when-let [base-entity (d/pull db api-key-base-pull-pattern [:api-key/id api-key-id])]
    (let [policy-id (get-in base-entity [:api-key/policy :access-policy/id])
          policy (when policy-id (pull-access-policy-entity db policy-id))
          prefetched-ref-attrs? (some #(contains? base-entity %)
                                      [:api-key/dataset-scopes
                                       :api-key/agent-refs
                                       :api-key/allowed-config-keys])]
      (normalize-key-entity
       (assoc base-entity
              :api-key/policy policy
              :api-key/dataset-scopes (cond
                                        (contains? base-entity :api-key/dataset-scopes)
                                        (:api-key/dataset-scopes base-entity)

                                        prefetched-ref-attrs?
                                        []

                                        :else
                                        (query-api-key-dataset-scopes db api-key-id))
              :api-key/agent-refs (cond
                                    (contains? base-entity :api-key/agent-refs)
                                    (:api-key/agent-refs base-entity)

                                    prefetched-ref-attrs?
                                    []

                                    :else
                                    (query-api-key-agent-refs db api-key-id))
              :api-key/allowed-config-keys (cond
                                             (contains? base-entity :api-key/allowed-config-keys)
                                             (:api-key/allowed-config-keys base-entity)

                                             prefetched-ref-attrs?
                                             []

                                             :else
                                             (query-api-key-allowed-config-keys db api-key-id)))))))

(defn- resolve-key-entity
  [db query-result]
  (cond
    (nil? query-result) nil
    (map? query-result) (normalize-key-entity query-result)
    :else (pull-api-key-entity db query-result)))

(defn- normalize-key-entity
  [key-entity]
  (let [policy (:api-key/policy key-entity)
        dataset-scopes (vec (distinct
                             (concat
                              (or (:access-policy/dataset-scopes policy) [])
                              (mapv (fn [dataset-scope]
                                      {:tenant (:api-key.dataset-scope/tenant dataset-scope)
                                       :dataset-config-key (:api-key.dataset-scope/dataset-config-key dataset-scope)})
                                    (:api-key/dataset-scopes key-entity)))))
        tenants (vec (distinct
                      (concat
                       (or (:access-policy/tenants policy) [])
                       (if (seq (:api-key/tenants key-entity))
                         (vec (:api-key/tenants key-entity))
                         (dataset-scopes->tenants (mapv (fn [dataset-scope]
                                                          {:tenant (:api-key.dataset-scope/tenant dataset-scope)
                                                           :dataset-config-key (:api-key.dataset-scope/dataset-config-key dataset-scope)})
                                                        (:api-key/dataset-scopes key-entity)))))))
        agent-refs (vec (distinct
                         (concat
                          (or (:access-policy/agent-refs policy) [])
                          (->> (:api-key/agent-refs key-entity)
                               (mapv :api-key.agent-ref/agent-id)))))
        allowed-config-keys (vec (distinct
                                  (concat
                                   (or (:access-policy/allowed-config-keys policy) [])
                                   (->> (:api-key/allowed-config-keys key-entity)
                                        (mapv normalize-pulled-allowed-config-key)
                                        vec))))]
    (-> key-entity
        (assoc :api-key/dataset-scopes dataset-scopes
               :api-key/agent-refs agent-refs
               :api-key/allowed-config-keys allowed-config-keys
               :api-key/tenants tenants
               :api-key/clients (vec (distinct (concat (or (:access-policy/clients policy) [])
                                                       (vec (:api-key/clients key-entity)))))
               :api-key/skill-graphs (vec (distinct (concat (or (:access-policy/skill-graphs policy) [])
                                                            (vec (:api-key/skill-graphs key-entity)))))
               :api-key/scopes (normalize-scopes (concat (or (:access-policy/scopes policy) [])
                                                         (:api-key/scopes key-entity)))))))

(defn- without-credential-material
  "Remove both current lookup material and any legacy plaintext from values
  returned to list/detail consumers."
  [key-entity]
  (dissoc key-entity :api-key/key :api-key/key-digest))


(defn create-access-policy!
  "Create a new access policy in the Datahike database.

  Args:
    conn - Datahike connection
    name - Descriptive name for the policy
    created-by - User ID of the person creating the policy
    opts - Map with:
           :clients - Collection of client IDs
           :dataset-scopes - Collection of explicit dataset access grants
           :agent-refs - Collection of explicit agent IDs
           :allowed-config-keys - Collection of allowed config keys
           :skill-graphs - Collection of allowed skill graph IDs
           :scopes - Set of scopes
  Returns:
    Map with :access-policy/id"
  ([conn name created-by]
   (create-access-policy! conn name created-by {}))
  ([conn name created-by {:keys [clients dataset-scopes agent-refs allowed-config-keys skill-graphs scopes]}]
   (let [policy-id (nano-id)
         now (.getTime (t/inst (t/now)))
         validated-scopes (or (seq (normalize-scopes scopes)) [:query])
         dataset-scopes-vec (normalize-dataset-scopes {:dataset-scopes dataset-scopes})
         agent-refs-vec (normalize-agent-refs agent-refs)
         allowed-config-keys-vec (normalize-allowed-config-keys allowed-config-keys)
         clients-vec (vec (or clients []))
         skill-graphs-vec (vec (or skill-graphs []))
         dataset-scope-tx-data (build-dataset-scope-tx-data dataset-scopes-vec)
         agent-ref-tx-data (build-agent-ref-tx-data agent-refs-vec)
         allowed-config-key-tx-data (build-allowed-config-key-tx-data conn allowed-config-keys-vec)
         policy-tx-data (cond-> {:access-policy/id policy-id
                                 :access-policy/name name
                                 :access-policy/created now
                                 :access-policy/created-by created-by
                                 :access-policy/scopes (vec validated-scopes)}
                          (seq clients-vec) (assoc :access-policy/clients clients-vec)
                          (seq skill-graphs-vec) (assoc :access-policy/skill-graphs skill-graphs-vec))
         create-tx-data (vec (concat dataset-scope-tx-data
                                     agent-ref-tx-data
                                     allowed-config-key-tx-data
                                     [policy-tx-data]))]
     (let [create-result (d/transact conn {:tx-data create-tx-data})
           db (or (:db-after create-result) @conn)
           policy-eid (resolve-eid-by-attr db :access-policy/id policy-id)
           dataset-scope-eids (resolve-eids-by-attr db :api-key.dataset-scope/id dataset-scope-tx-data)
           agent-ref-eids (resolve-eids-by-attr db :api-key.agent-ref/id agent-ref-tx-data)
           allowed-config-key-eids (resolve-eids-by-attr db :api-key.allowed-config-key/id allowed-config-key-tx-data)
           link-tx-data (vec (concat (build-parent-ref-assertions policy-eid :access-policy/dataset-scopes dataset-scope-eids)
                                     (build-parent-ref-assertions policy-eid :access-policy/agent-refs agent-ref-eids)
                                     (build-parent-ref-assertions policy-eid :access-policy/allowed-config-keys allowed-config-key-eids)))]
       (transact-ref-assertions! conn link-tx-data))
     {:access-policy/id policy-id})))

(defn get-access-policy-info
  "Get detailed information about an access policy by ID."
  [conn policy-id]
  (pull-access-policy-entity @conn policy-id))

(defn list-access-policies
  "List all access policies created by a specific user."
  [conn user-id]
  (let [db @conn
        policy-ids (d/q '[:find [?policy-id ...]
                          :in $ ?user-id
                          :where
                          [?e :access-policy/created-by ?user-id]
                          [?e :access-policy/id ?policy-id]]
                        db user-id)]
    (mapv #(pull-access-policy-entity db %) (sort policy-ids))))

(defn store-api-key
  "Store a new API key in the Datahike database.

  Args:
    conn - Datahike connection
    api-key - The plaintext API key
    name - Descriptive name for the key (e.g., 'Production API', 'Test Client')
    created-by - User ID of the person creating the key
    opts - Map with:
           :clients - Collection of client IDs (for cross-cutting authorization)
           :dataset-scopes - Collection of explicit dataset access grants: {:tenant \"...\" :dataset-config-key \"...\"}
           :agent-refs - Collection of explicit agent IDs
           :allowed-config-keys - Collection of allowed config keys using root-specific selectors, for example {:root :runtime :tenant \"...\" :runtime-config-key \"...\"}
           :skill-graphs - Collection of allowed skill graph IDs
           :scopes - Set of scopes #{:query :ingest :admin}, defaults to #{:query}
           :expires-at - Optional expiration timestamp (epoch ms)
           :user-email - Email of user creating the key (for audit)
  Returns:
    Map with :api-key-id and :api-key"
  ([conn api-key name created-by]
   (store-api-key conn api-key name created-by {}))
  ([conn api-key name created-by {:keys [policy-id clients dataset-scopes agent-refs allowed-config-keys skill-graphs scopes expires-at user-email]}]
   (let [api-key-id (nano-id)
         now (.getTime (t/inst (t/now)))
         
         ;; If policy-id is not provided but grants are, create a new policy
         effective-policy-id (or policy-id
                                 (when (or clients dataset-scopes agent-refs allowed-config-keys skill-graphs scopes)
                                   (:access-policy/id
                                    (create-access-policy! conn name created-by
                                                           {:clients clients
                                                            :dataset-scopes dataset-scopes
                                                            :agent-refs agent-refs
                                                            :allowed-config-keys allowed-config-keys
                                                            :skill-graphs skill-graphs
                                                            :scopes scopes}))))
         
         api-key-tx-data (cond-> (merge {:api-key/id api-key-id
                                  :api-key/key-digest (api-key-digest api-key)
                                  :api-key/name name
                                  :api-key/created now
                                  :api-key/created-by created-by
                                  :api-key/revoked false
                                  :api-key/usage-count 0}
                                        (api-key-display-metadata api-key))
                           effective-policy-id (assoc :api-key/policy [:access-policy/id effective-policy-id])
                           expires-at (assoc :api-key/expires-at expires-at))]
     (d/transact conn {:tx-data [api-key-tx-data]})
     
     ;; Audit log the creation
     (audit/log-api-key-change! conn
       {:action :create
        :api-key-id api-key-id
        :api-key-name name
        :policy-id effective-policy-id
        :user-email user-email
        :user-id created-by})
     {:api-key-id api-key-id
      :api-key api-key})))

(defn create-api-key!
  "Create a new API key with all parameters. This is a convenience function
   that generates the key and stores it in one atomic operation.

   Args:
     conn - Datahike connection
     key-name - Descriptive name for the key
     created-by - User ID of the person creating the key
     opts - Map with:
            :dataset-scopes - Collection of explicit dataset access grants: {:tenant \"...\" :dataset-config-key \"...\"}
            :agent-refs - Collection of explicit agent IDs
            :allowed-config-keys - Collection of allowed config keys using root-specific selectors, for example {:root :runtime :tenant \"...\" :runtime-config-key \"...\"}
            :skill-graphs - Collection of allowed skill graph IDs
            :scopes - Collection of scopes (will be converted to set and validated)
            :expires-in-days - Optional number of days until expiration (nil for no expiration)
            :user-email - Email of user creating the key (for audit)
   Returns:
     Map with :api-key (plaintext, shown only once) and :name"
  [conn key-name created-by {:keys [clients dataset-scopes agent-refs allowed-config-keys skill-graphs scopes expires-in-days user-email]}]
  (let [new-key (generate-api-key)
        expires-at (when (and expires-in-days (pos? expires-in-days))
                     (+ (System/currentTimeMillis)
                        (* expires-in-days 24 60 60 1000)))]
    (store-api-key conn
                   new-key
                   key-name
                   created-by
                   {:clients clients
                    :dataset-scopes dataset-scopes
                    :agent-refs agent-refs
                    :allowed-config-keys allowed-config-keys
                    :skill-graphs skill-graphs
                    :scopes (set scopes)
                    :expires-at expires-at
                    :user-email user-email})
    {:api-key new-key
     :name key-name}))

(defn validate-api-key
  "Validate an API key and return associated information if valid.

  Also updates the last-used timestamp and usage count as a side effect.

  Args:
    conn - Datahike connection
    api-key - The API key to validate

  Returns:
    Map with explicit grants and allowed config keys, nil otherwise

  Validation checks:
  - Key exists in database
  - Key is not revoked
  - Key is not expired"
  [conn api-key]
  (when api-key
    (let [db @conn
          digest (api-key-digest api-key)
          digest-match (api-key-id-by-digest db digest)
          legacy-match (when-not digest-match
                         (legacy-api-key-id-by-plaintext db api-key))
          normalized-key (resolve-key-entity db (or digest-match legacy-match))
          now (.getTime (t/inst (t/now)))
          expired? (when-let [expires-at (:api-key/expires-at normalized-key)]
                     (> now expires-at))]
      (when (and normalized-key
                 (not (:api-key/revoked normalized-key))
                 (not expired?))
        ;; Update usage and atomically upgrade a successfully authenticated
        ;; legacy row. Revoked/expired keys are deliberately not migrated by
        ;; this path because authentication did not succeed.
        (d/transact conn
                    {:tx-data (cond-> [(merge {:api-key/id (:api-key/id normalized-key)
                                               :api-key/last-used now
                                               :api-key/usage-count (inc (or (:api-key/usage-count normalized-key) 0))}
                                              (when legacy-match
                                                (merge {:api-key/key-digest digest}
                                                       (api-key-display-metadata api-key))))]
                                legacy-match
                                (conj [:db/retract
                                       [:api-key/id (:api-key/id normalized-key)]
                                       :api-key/key
                                       api-key]))})
        ;; Return key info
        {:dataset-scopes (:api-key/dataset-scopes normalized-key)
         :agent-refs (:api-key/agent-refs normalized-key)
         :allowed-config-keys (:api-key/allowed-config-keys normalized-key)
         :skill-graphs (:api-key/skill-graphs normalized-key)
         :tenants (vec (:api-key/tenants normalized-key))
         :client-id (first (:api-key/clients normalized-key))
         :api-key-id (:api-key/id normalized-key)
         :name (:api-key/name normalized-key)
         :scopes (set (normalize-scopes (:api-key/scopes normalized-key)))}))))

(defn api-key-stored?
  "True when `api-key` is present in hashed or legacy storage.

  Intended for idempotent bootstrap tooling; normal callers should use
  validate-api-key so revocation and expiry are enforced."
  [conn api-key]
  (when api-key
    (let [db @conn]
      (boolean (or (api-key-id-by-digest db (api-key-digest api-key))
                   (legacy-api-key-id-by-plaintext db api-key))))))

(defn migrate-legacy-api-key-storage!
  "Replace every legacy plaintext API-key value with its digest and display
  metadata. Safe to run repeatedly. Returns the number of migrated rows.

  Deployments may call this immediately after upgrading to eliminate dormant
  plaintext rows; active legacy keys are also migrated on successful use."
  [conn]
  (let [legacy-rows (d/q '[:find ?api-key-id ?plaintext
                           :where
                           [?e :api-key/id ?api-key-id]
                           [?e :api-key/key ?plaintext]]
                         @conn)]
    (doseq [[api-key-id plaintext] legacy-rows]
      (d/transact conn
                  {:tx-data [(merge {:api-key/id api-key-id
                                     :api-key/key-digest (api-key-digest plaintext)}
                                    (api-key-display-metadata plaintext))
                             [:db/retract [:api-key/id api-key-id]
                              :api-key/key plaintext]]}))
    (count legacy-rows)))

(defn- node-in-subtree?
  [db grant-node-id request-node-id]
  (loop [current-node-id request-node-id]
    (cond
      (nil? current-node-id) false
      (= grant-node-id current-node-id) true
      :else
      (recur (get-in (config-db/get-config-node db current-node-id)
                     [:config.node/parent :config.node/id])))))

(defn- node-ancestry-depth
  [db node-id]
  (loop [current-node-id node-id
         depth 0]
    (if-let [parent-id (get-in (config-db/get-config-node db current-node-id)
                               [:config.node/parent :config.node/id])]
      (recur parent-id (inc depth))
      depth)))

(defn find-matching-allowed-config-key
  "Return the nearest matching allowed config key for a requested root/tenant/node."
  [conn allowed-config-keys {:keys [root tenant node-id]}]
  (when node-id
    (->> (or allowed-config-keys [])
         (filter (fn [allowed-config-key]
                   (and (= root (:api-key.allowed-config-key/root allowed-config-key))
                        (= tenant (:api-key.allowed-config-key/tenant allowed-config-key))
                        (node-in-subtree? @conn
                                          (:api-key.allowed-config-key/node-id allowed-config-key)
                                          node-id))))
         (sort-by (fn [allowed-config-key]
                    (- (node-ancestry-depth @conn (:api-key.allowed-config-key/node-id allowed-config-key)))))
         first)))

(defn allowed-config-key-allows?
  "True when the API key allowed config keys allow the requested node."
  [conn allowed-config-keys request]
  (boolean (find-matching-allowed-config-key conn allowed-config-keys request)))

(defn require-allowed-config-key!
  "Throw when the API key allowed config keys do not allow the requested node."
  [conn allowed-config-keys {:keys [root tenant node-id] :as request}]
  (or (find-matching-allowed-config-key conn allowed-config-keys request)
      (throw (ex-info "API key is not allowed to access the requested config node"
                      {:status 403
                       :root root
                       :tenant tenant
                       :node-id node-id
                       :allowed-tenant-config-keys (->> (or allowed-config-keys [])
                                                        (filter #(and (= root (:api-key.allowed-config-key/root %))
                                                                      (= tenant (:api-key.allowed-config-key/tenant %))))
                                                        (map :api-key.allowed-config-key/tenant-config-key)
                                                        distinct
                                                        sort
                                                        vec)}))))

(defn revoke-api-key
  "Revoke an API key by ID. Does not delete the key (maintains audit trail).

  Args:
    conn - Datahike connection
    api-key-id - The ID of the API key to revoke
    opts - Optional map with :user-email and :user-id for audit logging

  Returns:
   Boolean - true if key was found and revoked, false otherwise"
  ([conn api-key-id]
   (revoke-api-key conn api-key-id {}))
  ([conn api-key-id {:keys [user-email user-id]}]
   (let [db @conn
         key-entity (pull-api-key-entity db api-key-id)]
     (when key-entity
       (d/transact conn
                   {:tx-data [{:api-key/id api-key-id
                               :api-key/revoked true}]})
       ;; Audit log the revocation
       (audit/log-api-key-change! conn
         {:action :revoke
          :api-key-id api-key-id
          :api-key-name (:api-key/name key-entity)
          :policy-id (get-in key-entity [:api-key/policy :access-policy/id])
          :dataset-scopes (:api-key/dataset-scopes key-entity)
          :agent-refs (:api-key/agent-refs key-entity)
          :user-email user-email
          :user-id user-id})
       true))))

(defn replace-access-policy-allowed-config-keys!
  "Replace the allowed config keys attached to an access policy."
  ([conn policy-id allowed-config-keys]
   (replace-access-policy-allowed-config-keys! conn policy-id allowed-config-keys {}))
  ([conn policy-id allowed-config-keys {:keys [_user-email _user-id]}]
   (let [db @conn
         policy-entity (pull-access-policy-entity db policy-id)]
     (when policy-entity
       (let [normalized-allowed-config-keys (normalize-allowed-config-keys allowed-config-keys)
             existing-allowed-config-key-eids (d/q '[:find [?allowed-config-key-eid ...]
                                                     :in $ ?policy-id
                                                     :where
                                                     [?p :access-policy/id ?policy-id]
                                                     [?p :access-policy/allowed-config-keys ?allowed-config-key-eid]]
                                                   db policy-id)
             replacement-allowed-config-key-tx (build-allowed-config-key-tx-data conn normalized-allowed-config-keys)
             retract-tx (mapv (fn [allowed-config-key-eid] [:db/retractEntity allowed-config-key-eid]) existing-allowed-config-key-eids)
             create-tx-data (vec replacement-allowed-config-key-tx)]
         (let [create-result (when (seq create-tx-data)
                               (d/transact conn {:tx-data create-tx-data}))
               updated-db (or (:db-after create-result) @conn)
               policy-eid (resolve-eid-by-attr updated-db :access-policy/id policy-id)
               replacement-allowed-config-key-eids (resolve-eids-by-attr updated-db
                                                                         :api-key.allowed-config-key/id
                                                                         replacement-allowed-config-key-tx)
               ref-assertions (build-parent-ref-assertions policy-eid
                                                           :access-policy/allowed-config-keys
                                                           replacement-allowed-config-key-eids)
               retract-only-tx-data (vec retract-tx)]
           (when (seq retract-only-tx-data)
             (d/transact conn {:tx-data retract-only-tx-data}))
           (transact-ref-assertions! conn ref-assertions))
         (pull-access-policy-entity @conn policy-id))))))

(defn replace-api-key-allowed-config-keys!
  "Replace the allowed config keys attached to an API key or its linked access policy."
  ([conn api-key-id allowed-config-keys]
   (replace-api-key-allowed-config-keys! conn api-key-id allowed-config-keys {}))
  ([conn api-key-id allowed-config-keys {:keys [user-email user-id] :as opts}]
   (let [db @conn
         key-entity (pull-api-key-entity db api-key-id)
         policy-id (get-in key-entity [:api-key/policy :access-policy/id])]
     (if policy-id
       (do
         (replace-access-policy-allowed-config-keys! conn policy-id allowed-config-keys opts)
         (pull-api-key-entity @conn api-key-id))
       (when key-entity
         (let [normalized-allowed-config-keys (normalize-allowed-config-keys allowed-config-keys)
               existing-allowed-config-key-eids (d/q '[:find [?allowed-config-key-eid ...]
                                                       :in $ ?api-key-id
                                                       :where
                                                       [?api-key :api-key/id ?api-key-id]
                                                       [?api-key :api-key/allowed-config-keys ?allowed-config-key-eid]]
                                                     db api-key-id)
               replacement-allowed-config-key-tx (build-allowed-config-key-tx-data conn normalized-allowed-config-keys)
               retract-tx (mapv (fn [allowed-config-key-eid] [:db/retractEntity allowed-config-key-eid]) existing-allowed-config-key-eids)
               create-tx-data (vec replacement-allowed-config-key-tx)]
           (let [create-result (when (seq create-tx-data)
                                 (d/transact conn {:tx-data create-tx-data}))
                 updated-db (or (:db-after create-result) @conn)
                 api-key-eid (resolve-eid-by-attr updated-db :api-key/id api-key-id)
                 replacement-allowed-config-key-eids (resolve-eids-by-attr updated-db
                                                                           :api-key.allowed-config-key/id
                                                                           replacement-allowed-config-key-tx)
                 ref-assertions (build-parent-ref-assertions api-key-eid
                                                             :api-key/allowed-config-keys
                                                             replacement-allowed-config-key-eids)
                 retract-only-tx-data (vec retract-tx)]
             (when (seq retract-only-tx-data)
               (d/transact conn {:tx-data retract-only-tx-data}))
             (transact-ref-assertions! conn ref-assertions))
           (audit/log-api-key-change! conn
                                      {:action :update
                                       :api-key-id api-key-id
                                       :api-key-name (:api-key/name key-entity)
                                       :dataset-scopes (:api-key/dataset-scopes key-entity)
                                       :agent-refs (:api-key/agent-refs key-entity)
                                       :previous-dataset-scopes (:api-key/dataset-scopes key-entity)
                                       :previous-agent-refs (:api-key/agent-refs key-entity)
                                       :user-email user-email
                                       :user-id user-id})
           (pull-api-key-entity @conn api-key-id)))))))


(defn rotate-api-key!
  "Rotate an API key by creating a new one with the same policy and revoking the old one.
   If the old key is a legacy key (no policy), a new policy will be created for it first."
  [conn old-api-key-id {:keys [_user-email user-id] :as opts}]
  (let [db @conn
        old-key-entity (pull-api-key-entity db old-api-key-id)]
    (if-not old-key-entity
      (throw (ex-info "API key not found" {:status 404 :api-key-id old-api-key-id}))
      (let [policy-id (get-in old-key-entity [:api-key/policy :access-policy/id])
            ;; Auto-create policy for legacy key during rotation
            effective-policy-id (or policy-id
                                    (:access-policy/id
                                     (create-access-policy! conn
                                                            (:api-key/name old-key-entity)
                                                            user-id
                                                            {:dataset-scopes (:api-key/dataset-scopes old-key-entity)
                                                             :agent-refs (:api-key/agent-refs old-key-entity)
                                                             :allowed-config-keys (:api-key/allowed-config-keys old-key-entity)
                                                             :skill-graphs (:api-key/skill-graphs old-key-entity)
                                                             :scopes (:api-key/scopes old-key-entity)
                                                             :clients (:api-key/clients old-key-entity)})))
            new-key (generate-api-key)
            result (store-api-key conn new-key (:api-key/name old-key-entity) user-id
                                   (assoc opts :policy-id effective-policy-id))]
        (revoke-api-key conn old-api-key-id opts)
        result))))

(defn migrate-legacy-keys-to-policies!
  "One-time migration to create policies for all existing API keys and link them.
   Returns the number of migrated keys."
  [conn]
  (let [db @conn
        legacy-key-ids (d/q '[:find [?api-key-id ...]
                              :where
                              [?e :api-key/id ?api-key-id]
                              (not [?e :api-key/policy])]
                            db)]
    (log/info "Migrating" (count legacy-key-ids) "legacy API keys to policies")
    (let [migrated-count (reduce (fn [acc api-key-id]
                                   (try
                                     (let [key-entity (pull-api-key-entity @conn api-key-id)
                                           policy-result (create-access-policy! conn
                                                                                (str (:api-key/name key-entity) " Policy")
                                                                                (or (:api-key/created-by key-entity) "system")
                                                                                {:clients (:api-key/clients key-entity)
                                                                                 :dataset-scopes (:api-key/dataset-scopes key-entity)
                                                                                 :agent-refs (:api-key/agent-refs key-entity)
                                                                                 :allowed-config-keys (:api-key/allowed-config-keys key-entity)
                                                                                 :skill-graphs (:api-key/skill-graphs key-entity)
                                                                                 :scopes (set (:api-key/scopes key-entity))})
                                           policy-id (:access-policy/id policy-result)]
                                       (d/transact conn {:tx-data [[:db/add [:api-key/id api-key-id] :api-key/policy [:access-policy/id policy-id]]]})
                                       (inc acc))
                                     (catch Exception e
                                       (log/error e "Failed to migrate API key" {:api-key-id api-key-id})
                                       acc)))
                                 0
                                 legacy-key-ids)]
      (log/info "Successfully migrated" migrated-count "API keys")
      migrated-count)))

(defn list-api-keys
  "List all API keys created by a specific user.

  Args:
    conn - Datahike connection
    user-id - User ID to filter by

  Returns:
    Vector of maps with API key information (without the actual key)"
  [conn user-id]
  (let [db @conn
        results (api-key-ids-by-created-by db user-id)]
    (if (every? map? results)
      (mapv #(-> % normalize-key-entity without-credential-material) results)
      (->> results
           sort
           (mapv #(some-> (pull-api-key-entity db %)
                          without-credential-material))))))

(defn list-all-api-keys
  "List all API keys in the system (admin function).

  Args:
    db - Datahike db value

  Returns:
    Vector of maps with API key information and non-secret display metadata.
    Note: scopes are converted to vectors for Transit serialization compatibility."
  [db]
  (->> (d/q '[:find [?api-key-id ...]
              :where
              [?e :api-key/id ?api-key-id]]
            db)
       sort
       (mapv #(some-> (pull-api-key-entity db %)
                      without-credential-material))))

(defn export-all-api-keys
  "Return portable API-key records. Exports include one-way digests so existing
  credentials continue working after restore, but never include plaintext."
  [db]
  (->> (d/q '[:find [?api-key-id ...]
              :where
              [?e :api-key/id ?api-key-id]]
            db)
       sort
       (mapv #(-> (pull-api-key-entity db %)
                  (dissoc :api-key/key)))))

(defn get-api-key-info
  "Get detailed information about an API key by ID.

  Args:
    conn - Datahike connection
    api-key-id - The ID of the API key

  Returns:
    Map with API key information (without the actual key)"
  [conn api-key-id]
  (let [db @conn]
    (some-> (resolve-key-entity
             db
             (d/q '[:find ?api-key-id .
                    :in $ ?api-key-id
                    :where
                    [?e :api-key/id ?api-key-id]]
                  db api-key-id))
            without-credential-material)))

(comment
  ;; Usage examples

  ;; Generate a new API key
  (def new-key (generate-api-key))
  ;; => "rag_a1b2c3d4..."

  ;; Store it in the database with multi-tenant dataset grants.
  (def conn (db/get-conn))
  (def result (store-api-key conn new-key "Test API Key" "user-123"
                             {:dataset-scopes [{:tenant "ka" :dataset-config-key "prod"}]
                              :scopes #{:query :ingest}}))
  ;; => {:api-key-id "abc123", :api-key "rag_a1b2c3d4..."}

  ;; Create key with convenience function
  (create-api-key! conn "My Key" "user-123"
                   {:dataset-scopes [{:tenant "ka" :dataset-config-key "prod"}]
                    :scopes [:query]
                    :expires-in-days 30})
  ;; => {:api-key "rag_...", :name "My Key"}

  ;; Validate the key
  (validate-api-key conn new-key)
  ;; => {:tenants ["ka"], :dataset-scopes [{:tenant "ka" ...}], ...}

  ;; List keys for a user
  (list-api-keys conn "user-123")
  ;; => [{:api-key/id "abc123", :api-key/name "Test API Key", ...}]

  ;; Revoke a key
  (revoke-api-key conn "abc123")
  ;; => true

  ;; Try to validate revoked key
  (validate-api-key conn new-key)
  ;; => nil
  )
